# Use Python 3.9 image
FROM python:3.9-slim

# Set working directory
WORKDIR /app

# Install necessary packages
COPY requirements.txt .
RUN pip install -r requirements.txt

# Copy the producer code into the container
COPY order_publisher.py .

# Command to run the producer
CMD ["python", "order_publisher.py"]
