version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - order-network

  producer:
    build:
      context: .
      dockerfile: Dockerfile.producer
    container_name: order-producer
    depends_on:
      - redis
    networks:
      - order-network
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    restart: always

  consumer:
    build:
      context: .
      dockerfile: Dockerfile.consumer
    container_name: order-consumer
    depends_on:
      - redis
      - model-service
    networks:
      - order-network
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MODEL_SERVICE_URL=http://model-service:5001/predict

    restart: always

  model-service:
    build:
      context: .
      dockerfile: Dockerfile.model
    container_name: model-service
    ports:
      - "5001:5001"  # Expose it for external testing, optional
    networks:
      - order-network
    restart: always

networks:
  order-network:
    driver: bridge
