# Use Python 3.9 image
FROM python:3.9-slim

# Set working directory
WORKDIR /app

# Install necessary packages
COPY requirements.txt .
RUN pip install -r requirements.txt

# Copy the consumer code into the container
COPY order_consumer.py .

# Command to run the consumer
CMD ["python", "order_consumer.py"]
